### ISSUE TITLE
kvm kitchen test has an error

### ISSUE THREAD

**Issue by aidda** [chef-cookbooks/ntp#163]
I downloded kvm from supermarket. Then I did kitchen converge and I saw this error:

```
================================================================================
       Recipe Compile Error
       ================================================================================
       
       Chef::Exceptions::RecipeNotFound
       --------------------------------
       could not find recipe disable for cookbook ntp
       
       Cookbook Trace:
       ---------------
         /tmp/kitchen/cache/cookbooks/kvm/recipes/guest.rb:26:in `from_file'
         /tmp/kitchen/cache/cookbooks/kvm/recipes/default.rb:21:in `from_file'
         /tmp/kitchen/cache/cookbooks/gtd_buildhost/recipes/default.rb:12:in `from_file'
       
       Relevant File Content:
       ----------------------
       /tmp/kitchen/cache/cookbooks/kvm/recipes/guest.rb:
       
        19:  #
        20:  
        21:  ## Use kvm-clock
        22:  # http://s19n.net/articles/2011/kvm_clock.html
        23:  # Disabling NTP is recommended when using kvm-clock
        24:  if node['os'] == 'linux' && node['kernel']['release'] >= '2.6.27'
        25:    node.override['ntp']['ntpdate']['disable'] = false
        26>>   include_recipe 'ntp::disable'
        27:    include_recipe 'ntp::ntpdate'
        28:  else
        29:    include_recipe 'ntp'
        30:  end
        31:  
       
       System Info:
       ------------
       chef_version=13.0.118
       platform=centos
       platform_version=7.3.1611
       ruby=ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-linux]
       program_name=chef-client worker: ppid=12076;start=20:02:27;
       executable=/opt/chef/bin/chef-client
       
       
       Running handlers:
       [2017-05-10T20:02:30+00:00] ERROR: Running exception handlers
       [2017-05-10T20:02:30+00:00] ERROR: Running exception handlers
       Running handlers complete
       [2017-05-10T20:02:30+00:00] ERROR: Exception handlers complete
       [2017-05-10T20:02:30+00:00] ERROR: Exception handlers complete
       Chef Client failed. 0 resources updated in 03 seconds
       [2017-05-10T20:02:30+00:00] FATAL: Stacktrace dumped to /tmp/kitchen/cache/chef-stacktrace.out
       [2017-05-10T20:02:30+00:00] FATAL: Stacktrace dumped to /tmp/kitchen/cache/chef-stacktrace.out
       [2017-05-10T20:02:30+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
       [2017-05-10T20:02:30+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
       [2017-05-10T20:02:30+00:00] ERROR: could not find recipe disable for cookbook ntp
       [2017-05-10T20:02:30+00:00] ERROR: could not find recipe disable for cookbook ntp
       [2017-05-10T20:02:30+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
       [2017-05-10T20:02:30+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: 1 actions failed.
>>>>>>     Converge failed on instance <default-rhel7>.  Please see .kitchen/logs/default-rhel7.log for more details
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuratio
```
Based on my investigation, it is only realed to ntp cookbook and kvm. But I cant understand what is a problem. Also, I used my custom box which I created woth packer and libvirt provider.
I installed the last version of Chef-DK for Ubuntu 16.04 which is chefdk_1.3.43-1
chef-client: 12.19.36
berks -v: 5.6.4
Test kitchen -v: 1.16.0

**Comment by shortdudey123** [comment]
`ntp::disable` was removed 4 yrs ago.
The `kvm` owner needs to update their cookbook

**Comment by aidda** [comment]
@shortdudey123 so I have to delete that recipe?

**Comment by tas50** [comment]
@aidda Yes that should be removed from the KVM cookbook

**Comment by aidda** [comment]
@shortdudey123 OMG I was searching for this issue about two hours! thanks a lot!
I did it, and now it`s fine
